CREATE DATABASE  hotel_alura;

USE hotel_alura;

CREATE TABLE USERS(
    id INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50),
    APELLIDO VARCHAR(50),
    USUARIO VARCHAR(50),
    password VARCHAR(250),
    PRIMARY KEY(id)
);




CREATE TABLE huespedes(
    ID INT AUTO_INCREMENT NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    F_NACIMIENTO DATE,
    NACIONALIDAD VARCHAR(70),
    TELEFONO VARCHAR(12),
    ID_RESERVA INT NOT NULL,
    PRIMARY KEY(ID),
    FOREIGN KEY (ID_RESERVA) REFERENCES RESERVAS(ID)

);

CREATE TABLE RESERVAS(
    ID INT AUTO_INCREMENT NOT NULL,
    FECHA_ENTRADA DATE ,
    FECHA_SALIDA DATE,
    VALOR DECIMAL(4,2) NOT NULL,
    FORMA_PAGO SET('Tarjeta de Crédito', 'Tarjeta de Débito', 'Dinero en efectivo'),
    PRIMARY KEY(ID)
);

